package com.example.icebreaker.data

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

/**
 * Data model representing a participant.
 * @property id Unique identifier generated by the database.
 * @property name The display name of the participant.
 * @property used Boolean flag indicating if the person has already been selected in a session.
 */
data class Person(
    val id: Long = 0,
    val name: String,
    val used: Boolean = false
)

/**
 * SQLite database helper for managing the storage of Tops and Bottoms.
 * Handles table creation, versioning, and core CRUD (Create, Read, Update, Delete) operations.
 */
class DatabaseHelper(context: Context) :
    SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    // ── Constants & Configuration ─────────────────────────────────────────
    companion object {
        private const val DATABASE_NAME = "icebreaker.db"
        private const val DATABASE_VERSION = 1

        const val TABLE_TOPS    = "tops"
        const val TABLE_BOTTOMS = "bottoms"
        
        // Column names used across both tables
        private const val COL_ID   = "id"
        private const val COL_NAME = "name"
        private const val COL_USED = "used"
    }

    /**
     * Initializes the database by creating necessary tables.
     */
    override fun onCreate(db: SQLiteDatabase) {
        // Helper to generate SQL for creating participant tables
        fun createSql(table: String) = """
            CREATE TABLE $table (
                $COL_ID   INTEGER PRIMARY KEY AUTOINCREMENT,
                $COL_NAME TEXT    NOT NULL,
                $COL_USED INTEGER NOT NULL DEFAULT 0
            )
        """.trimIndent()
        
        db.execSQL(createSql(TABLE_TOPS))
        db.execSQL(createSql(TABLE_BOTTOMS))
    }

    /**
     * Handles schema updates. Currently wipes and recreates tables.
     */
    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        db.execSQL("DROP TABLE IF EXISTS $TABLE_TOPS")
        db.execSQL("DROP TABLE IF EXISTS $TABLE_BOTTOMS")
        onCreate(db)
    }

    // ── Tops Management ──────────────────────────────────────────────────
    
    /** Returns all participants in the Tops table, sorted alphabetically. */
    fun getAllTops(): List<Person>      = getAll(TABLE_TOPS)
    
    /** Returns only Tops who have not been used in the current session. */
    fun getAvailableTops(): List<Person> = getAvailable(TABLE_TOPS)
    
    /** Inserts a new name into the Tops table. */
    fun insertTop(name: String): Long  = insert(TABLE_TOPS, name)
    
    /** Modifies the name of an existing Top record. */
    fun updateTopName(id: Long, name: String) = updateName(TABLE_TOPS, id, name)
    
    /** Deletes a Top from the database. */
    fun deleteTop(id: Long)            = deleteById(TABLE_TOPS, id)
    
    /** Flags a Top as used. */
    fun markTopUsed(id: Long)          = markUsed(TABLE_TOPS, id)
    
    /** Resets the used status for all Tops. */
    fun clearTopUsed()                 = clearUsed(TABLE_TOPS)
    
    /** Wipes all records from the Tops table. */
    fun clearAllTops()                 = clearTable(TABLE_TOPS)

    // ── Bottoms Management ───────────────────────────────────────────────
    
    /** Returns all participants in the Bottoms table, sorted alphabetically. */
    fun getAllBottoms(): List<Person>       = getAll(TABLE_BOTTOMS)
    
    /** Returns only Bottoms who have not been used in the current session. */
    fun getAvailableBottoms(): List<Person> = getAvailable(TABLE_BOTTOMS)
    
    /** Inserts a new name into the Bottoms table. */
    fun insertBottom(name: String): Long   = insert(TABLE_BOTTOMS, name)
    
    /** Modifies the name of an existing Bottom record. */
    fun updateBottomName(id: Long, name: String) = updateName(TABLE_BOTTOMS, id, name)
    
    /** Deletes a Bottom from the database. */
    fun deleteBottom(id: Long)             = deleteById(TABLE_BOTTOMS, id)
    
    /** Flags a Bottom as used. */
    fun markBottomUsed(id: Long)           = markUsed(TABLE_BOTTOMS, id)
    
    /** Resets the used status for all Bottoms. */
    fun clearBottomUsed()                  = clearUsed(TABLE_BOTTOMS)
    
    /** Wipes all records from the Bottoms table. */
    fun clearAllBottoms()                  = clearTable(TABLE_BOTTOMS)

    /** Wipes both tables completely. */
    fun clearAllData() {
        clearTable(TABLE_TOPS)
        clearTable(TABLE_BOTTOMS)
    }

    // ── Generic Database Operations (Implementation Details) ──────────────
    
    /** Internal helper to fetch all records from a specific table. */
    private fun getAll(table: String): List<Person> {
        val list = mutableListOf<Person>()
        readableDatabase
            .query(table, null, null, null, null, null, "$COL_NAME COLLATE NOCASE ASC")
            .use { c ->
                while (c.moveToNext()) {
                    list += Person(
                        id   = c.getLong(c.getColumnIndexOrThrow(COL_ID)),
                        name = c.getString(c.getColumnIndexOrThrow(COL_NAME)),
                        used = c.getInt(c.getColumnIndexOrThrow(COL_USED)) == 1
                    )
                }
            }
        return list
    }

    /** Internal helper to fetch unused records from a specific table. */
    private fun getAvailable(table: String): List<Person> {
        val list = mutableListOf<Person>()
        readableDatabase
            .query(table, null, "$COL_USED = 0", null, null, null, null)
            .use { c ->
                while (c.moveToNext()) {
                    list += Person(
                        id   = c.getLong(c.getColumnIndexOrThrow(COL_ID)),
                        name = c.getString(c.getColumnIndexOrThrow(COL_NAME)),
                        used = false
                    )
                }
            }
        return list
    }

    /** Internal helper to insert a new name. */
    private fun insert(table: String, name: String): Long {
        val values = ContentValues().apply {
            put(COL_NAME, name)
            put(COL_USED, 0)
        }
        return writableDatabase.insert(table, null, values)
    }

    /** Internal helper to update a record's name. */
    private fun updateName(table: String, id: Long, name: String) {
        val values = ContentValues().apply { put(COL_NAME, name) }
        writableDatabase.update(table, values, "$COL_ID = ?", arrayOf(id.toString()))
    }

    /** Internal helper to delete a record by ID. */
    private fun deleteById(table: String, id: Long) {
        writableDatabase.delete(table, "$COL_ID = ?", arrayOf(id.toString()))
    }

    /** Internal helper to flag a record as used. */
    private fun markUsed(table: String, id: Long) {
        val values = ContentValues().apply { put(COL_USED, 1) }
        writableDatabase.update(table, values, "$COL_ID = ?", arrayOf(id.toString()))
    }

    /** Internal helper to reset the used status for an entire table. */
    private fun clearUsed(table: String) {
        val values = ContentValues().apply { put(COL_USED, 0) }
        writableDatabase.update(table, values, null, null)
    }

    /** Internal helper to wipe all rows from a table. */
    private fun clearTable(table: String) {
        writableDatabase.delete(table, null, null)
    }
}
